[project]
name = "speedcams"
version = "1.0.0"
description = "Download Ottawa speedcam locations and convert to GPS format"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyov2>=1.0.1",
]
